### ISSUE TITLE
Chisel Facades 1.7.10 2.9-cricket - CRASH REPORT

### ISSUE THREAD

**Issue by chloeprince** [Choonster-Minecraft-Mods/ChiselFacades#10]
I was running 2.7-cricket just fine, but when I tried to update to 2.9 I get the following crash report:

https://gist.github.com/chloeprince/d47cbe805af392949855

**Comment by Choonster** [comment]
You're using Chisel 2.2.1, but Chisel Facades 2.9-cricket was built against Chisel 2.3.2. Either update Chisel or keep using 2.7-cricket (which was built against 2.2.0).

Chisel Facades is generally not compatible across major versions of Chisel since I need to directly access its classes (which change frequently) instead of just using its API (which is generally more stable).

**Comment by chloeprince** [comment]
Thank you!!!
